import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'sb-cap-001',
    sku: 'SB-CAP-001',
    title: 'The "Sponsor Backed" Chino Cap',
    subtitle: 'The Flagship',
    handle: 'sponsor-backed-cap',
    category: 'caps',
    price: 64.0,
    colorway: 'Boardroom Navy',
    threadColor: 'Ecru Collegiate Serif',
    undervisorColor: 'Augusta Green Cotton Twill',
    fabrication: '100% Long-Staple Cotton Chino Twill (7.5 oz, Stone Enzyme Washed)',
    hardware: 'Solid Antique Brass Tri-Glide Slider with Tuck-in Grommet',
    description:
      'Being "sponsor-backed" means your enterprise is fortified by top-tier institutional equity. Worn on the weekend, it\'s an understated nod to the buy-side.',
    catalogStory:
      'We start with 100% long-staple cotton chino twill, put it through a 45-minute stone enzyme wash, and stitch "SPONSOR BACKED" arched across the crown in vintage ecru thread. The underside of the bill features our signature dark Augusta Green cotton twill.',
    stylingNotes:
      'An unbuttoned pale-blue Oxford, weathered chinos, and an early morning coffee run before markets open.',
    images: ['/images/sponsor_backed_cap.jpg', '/images/lifestyle_cap_desk.jpg', '/images/lifestyle_cap_portrait.jpg', '/images/detail_macro_brass.jpg'],
    badges: ['Flagship'],
    inStock: true,
    featured: true,
    specs: [
      { label: 'Crown', value: 'Low-profile unstructured 6-panel' },
      { label: 'Embroidery', value: 'Chain-stitched collegiate arch' },
      { label: 'Hardware', value: 'Antique brass tri-glide slider' },
      { label: 'Undervisor', value: 'Augusta Green cotton twill' },
    ],
    sizes: ['One Size (Adjustable)'],
  },
  {
    id: 'sb-cap-002',
    sku: 'SB-CAP-002',
    title: 'The "EBITDA" Braided Rope Cap',
    subtitle: 'Country Club Edition',
    handle: 'ebitda-rope-hat',
    category: 'caps',
    price: 68.0,
    colorway: 'Augusta Cypress Green',
    threadColor: 'Bone Athletic Serif',
    undervisorColor: 'Matching Cypress Green',
    fabrication: 'Water-resistant matte-finish performance poly-cotton blend',
    hardware: 'Retro perforated snapback',
    description:
      'The foundational financial metric meets the golden age of country club golf. Built with a 5-panel crown and authentic braided chalk cord across the visor seam.',
    catalogStory:
      'Whether you\'re breaking 80 on a Friday partner scramble or debating the merits of non-recurring add-backs over lunch at the grill, this cap signals instant belonging.',
    stylingNotes:
      'A pique polo and tortoiseshell sunglasses on the fairway.',
    images: ['/images/ebitda_rope_hat.jpg'],
    badges: ['Country Club'],
    inStock: true,
    featured: true,
    specs: [
      { label: 'Crown', value: 'Medium-profile 5-panel pinch-front' },
      { label: 'Rope', value: '5mm braided chalk-white cotton cord' },
      { label: 'Embroidery', value: 'Flat satin-stitch lettering' },
      { label: 'Sweatband', value: 'Moisture-wicking micro-terry' },
    ],
    sizes: ['One Size (Adjustable Snapback)'],
  },
  {
    id: 'sb-cap-003',
    sku: 'SB-CAP-003',
    title: 'The "Dry Powder" Chino Cap',
    subtitle: 'Classic Allocator',
    handle: 'dry-powder-cap',
    category: 'caps',
    price: 64.0,
    colorway: 'Deep Midnight Navy',
    threadColor: 'Vintage Cream Roman Serif',
    undervisorColor: 'Augusta Green Cotton Twill',
    fabrication: '100% Long-Staple Cotton Chino Twill (Stone Washed)',
    hardware: 'Solid Antique Brass Tri-Glide Slider',
    description:
      'Uninvested capital waiting on the sidelines to be deployed. A double meaning evoking classic dry goods merchants and unyielding liquidity.',
    catalogStory:
      'Inspired by the weathered ballcaps tossed onto the passenger seats of vintage Wagoneers parked outside Maidstone Club. Cut from washed chino twill with chain-stitched typography that feels broken-in from day one.',
    stylingNotes: 'A heavy knit Shetland crewneck or a vintage canvas chore coat.',
    images: ['/images/dry_powder_cap.jpg'],
    badges: ['Core'],
    inStock: true,
    featured: true,
    specs: [
      { label: 'Crown', value: 'Low-profile unstructured 6-panel' },
      { label: 'Lettering', value: 'Arched Roman serif' },
      { label: 'Hardware', value: 'Antique brass slider' },
      { label: 'Undervisor', value: 'Augusta Green twill' },
    ],
    sizes: ['One Size (Adjustable)'],
  },
  {
    id: 'sb-cap-004',
    sku: 'SB-CAP-004',
    title: 'The "Pls Fix" Cap',
    subtitle: 'The 11:42 PM Email',
    handle: 'pls-fix-cap',
    category: 'caps',
    price: 58.0,
    colorway: 'Washed Slate Grey',
    threadColor: 'Midnight Navy Micro-Stitch',
    undervisorColor: 'Augusta Green Cotton Twill',
    fabrication: '100% Brushed Chino Cotton Twill',
    hardware: 'Matte Brushed Pewter Slider',
    description:
      'The two-word sign-off sent by partners from the backseat of an Uber at 11:42 PM. Rendered in a tiny typewriter font that is intentionally discreet.',
    catalogStory:
      'To anyone outside the industry, it\'s just two lowercase words. To anyone who has spent a Saturday night aligning footnotes in an Investment Committee memo, it is pure, shared catharsis.',
    stylingNotes: 'Quiet, wry, and understated with an unbuttoned OCBD.',
    images: ['/images/pls_fix_cap.jpg'],
    badges: ['Cult Favorite'],
    inStock: true,
    specs: [
      { label: 'Typography', value: '0.45" lowercase Courier micro-embroidery' },
      { label: 'Crown', value: 'Unstructured 6-panel relaxed fit' },
      { label: 'Hardware', value: 'Matte brushed pewter slider' },
    ],
    sizes: ['One Size (Adjustable)'],
  },
  {
    id: 'sb-cap-005',
    sku: 'SB-CAP-005',
    title: 'The "2 & 20" Stealth Cap',
    subtitle: 'Tonal Black-on-Black',
    handle: 'two-and-twenty-cap',
    category: 'caps',
    price: 62.0,
    colorway: 'Weathered Charcoal',
    threadColor: 'Tonal Black 3D Puff',
    undervisorColor: 'Charcoal Cotton Twill',
    fabrication: '100% Heavy-Washed Charcoal Chino Twill',
    hardware: 'Gunmetal Slider Buckle',
    description:
      'Two percent management fee, twenty percent carried interest. Stitched in subtle tonal embroidery for pure stealth-wealth authority.',
    catalogStory:
      'From five paces away, it appears to be a clean, unadorned black cap. Up close, it commands instant respect from fellow fund managers.',
    stylingNotes: 'Cashmere half-zip and dark denim on private departures.',
    images: ['/images/two_and_twenty_cap.jpg'],
    badges: ['Stealth'],
    inStock: true,
    specs: [
      { label: 'Front', value: 'Tonal 3D puff "2 & 20"' },
      { label: 'Rear', value: 'Micro-embroidered "SB" monogram' },
      { label: 'Hardware', value: 'Gunmetal slider buckle' },
    ],
    sizes: ['One Size (Adjustable)'],
  },
  {
    id: 'sb-cap-006',
    sku: 'SB-CAP-006',
    title: 'The "Carried Interest" Corduroy Cap',
    subtitle: 'Autumn Limited',
    handle: 'carried-interest-corduroy',
    category: 'caps',
    price: 68.0,
    colorway: 'Oxblood Merlot',
    threadColor: 'Vintage Antique Gold Cursive',
    undervisorColor: 'Matching Oxblood Corduroy',
    fabrication: '100% Fine-Wale Cotton Corduroy (14-wale)',
    hardware: 'Solid Antique Brass Buckle',
    description:
      'The GP\'s 20% share of fund profits. Cut from substantial 14-wale cotton corduroy in a deep autumn wine tone.',
    catalogStory:
      'Evokes leather wingback chairs and October flights to Boston. Embroidered with "Carried Interest" in an elegant cursive script that looks more like a private society emblem than a finance term.',
    stylingNotes: 'Heavy cable-knit sweaters and espresso during Q4 deal sprints.',
    images: ['/images/carried_interest_cap.jpg'],
    badges: ['Autumn Limited'],
    inStock: true,
    specs: [
      { label: 'Fabric', value: '100% Cotton 14-Wale Corduroy' },
      { label: 'Embroidery', value: 'Vintage gold heritage script' },
      { label: 'Hardware', value: 'Antique brass tri-glide slider' },
    ],
    sizes: ['One Size (Adjustable)'],
  },
  {
    id: 'sb-cap-007',
    sku: 'SB-CAP-007',
    title: 'The "LBO Athletic Club" Cap',
    subtitle: 'Ivy League Heritage',
    handle: 'lbo-athletic-club-cap',
    category: 'caps',
    price: 64.0,
    colorway: 'Southampton Chalk',
    threadColor: 'Boardroom Navy Collegiate Block',
    undervisorColor: 'Augusta Green Cotton Twill',
    fabrication: 'Unbleached Natural Ecru Cotton Twill with Navy Visor Stitching',
    hardware: 'Solid Antique Brass Buckle with Engraved Crest',
    description:
      'An ironic homage to vintage Ivy League squash and crew societies. Arched athletic block lettering across unbleached chalk-white cotton twill.',
    catalogStory:
      'Feels straight out of a 1991 Cambridge sporting goods store. The "LBO Athletic Club" is, of course, entirely fictional — but the craftsmanship is very real.',
    stylingNotes: 'A navy blazer thrown over a striped rugby and chinos at the club.',
    images: ['/images/lbo_athletic_club_cap.jpg'],
    badges: ['Heritage'],
    inStock: true,
    featured: true,
    specs: [
      { label: 'Fabric', value: 'Unbleached natural ecru cotton twill' },
      { label: 'Embroidery', value: 'Arched collegiate block typography' },
      { label: 'Hardware', value: 'Antique brass with crossed-pens crest' },
    ],
    sizes: ['One Size (Adjustable)'],
  },
  {
    id: 'sb-cap-008',
    sku: 'SB-CAP-008',
    title: 'The "Wire Sent" Chino Cap',
    subtitle: 'The Closing Call',
    handle: 'wire-sent-cap',
    category: 'caps',
    price: 62.0,
    colorway: 'Faded Olive',
    threadColor: 'Chalk White Clean Serif',
    undervisorColor: 'Augusta Green Cotton Twill',
    fabrication: '100% Garment-Washed Cotton Chino Twill',
    hardware: 'Antique Brass Tri-Glide Slider',
    description:
      'The two most beautiful words in private equity. When the wire clears, the deal is done. Worn to celebrate closings and weekends that follow.',
    catalogStory:
      'In a garment-dyed olive wash that evokes vintage military surplus, "WIRE SENT" is stitched across the crown in clean chalk-white serif. The cap you reach for the Friday after a deal closes.',
    stylingNotes: 'A classic celebratory drink at the dark-paneled bar with the deal team.',
    images: ['/images/wire_sent_cap.jpg'],
    badges: ['New'],
    inStock: true,
    specs: [
      { label: 'Crown', value: 'Low-profile unstructured 6-panel' },
      { label: 'Wash', value: 'Heavy garment-dyed olive enzyme wash' },
      { label: 'Hardware', value: 'Antique brass tri-glide slider' },
    ],
    sizes: ['One Size (Adjustable)'],
  },
  {
    id: 'sb-tee-101',
    sku: 'SB-TEE-101',
    title: 'The "Adjusted EBITDA*" Pocket Tee',
    subtitle: '260 GSM Heavyweight',
    handle: 'adjusted-ebitda-tee',
    category: 'apparel',
    price: 54.0,
    colorway: 'Southampton Chalk White',
    threadColor: 'Navy Micro-Serif with Antique Brass Asterisk',
    undervisorColor: 'N/A',
    fabrication: '100% Ring-Spun Combed Cotton (260 GSM / 7.7 oz)',
    hardware: 'Hand-Stitched Woven Dallas Hem Tag',
    description:
      'A heavyweight tee with structure, weight, and zero cling. Dense 260 GSM combed cotton that washes down into an incredibly soft vintage hand.',
    catalogStory:
      'Features a reinforced chest pocket crowned with our discreet micro-embroidered mark: "ADJUSTED*" with the asterisk subtly rendered in golden brass thread.',
    stylingNotes: 'Rolled chinos or swim trunks on Summer Fridays.',
    images: ['/images/adjusted_ebitda_tee.jpg'],
    badges: ['Heavyweight'],
    inStock: true,
    specs: [
      { label: 'Weight', value: '260 GSM / 7.7 oz Combed Cotton' },
      { label: 'Collar', value: '1" ribbed crewneck that holds shape' },
      { label: 'Fit', value: 'Classic relaxed boxy cut with drop shoulder' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'sb-polo-102',
    sku: 'SB-POLO-102',
    title: 'The "Proprietary Deal Flow" Polo',
    subtitle: 'Heavyweight Pique Cotton',
    handle: 'proprietary-deal-flow-polo',
    category: 'apparel',
    price: 78.0,
    colorway: 'Collegiate Navy',
    threadColor: 'Ecru Micro-Crest Embroidery',
    undervisorColor: 'N/A',
    fabrication: '100% Long-Staple Pique Cotton (240 GSM)',
    hardware: 'Mother-of-Pearl Buttons',
    description:
      'A substantial pique polo with a small embroidered crest on the left chest — understated enough for client dinners, sharp enough for the links.',
    catalogStory:
      'Cut from dense 240 GSM pique cotton with a tailored mid-length collar that sits clean with or without a blazer. The left chest carries a discreet Sponsor Backed crest.',
    stylingNotes: 'Layered under a navy blazer at an offsite, or worn solo on the terrace.',
    images: ['/images/proprietary_deal_flow_polo.jpg'],
    badges: ['New'],
    inStock: true,
    specs: [
      { label: 'Weight', value: '240 GSM Long-Staple Pique Cotton' },
      { label: 'Collar', value: 'Tailored mid-length ribbed collar' },
      { label: 'Buttons', value: 'Mother-of-pearl, 3-button placket' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'sb-swt-201',
    sku: 'SB-SWT-201',
    title: 'The "Sunday Night Deck" Sweatshirt',
    subtitle: '450 GSM French Terry',
    handle: 'sunday-night-deck-sweatshirt',
    category: 'apparel',
    price: 118.0,
    colorway: 'Collegiate Navy',
    threadColor: 'Tonal Monogram Cuff Stitch',
    undervisorColor: 'N/A',
    fabrication: '450 GSM 100% Cotton Loopback French Terry (Cross-Grain Cut)',
    hardware: 'Ribbed V-Notch Collar Insert',
    description:
      'Named after the quiet Sunday evening ritual of putting the final touches on Monday morning\'s presentation.',
    catalogStory:
      'Crafted from substantial 450 GSM cross-grain loopback French terry with heavy ribbed side gussets. It has the weight, drape, and warmth of classic collegiate athletic fleeces.',
    stylingNotes: 'Layered over an Oxford with broken-in fatigues or grey flannel trousers.',
    images: ['/images/sunday_night_deck_sweatshirt.jpg'],
    badges: ['Heavyweight'],
    inStock: true,
    specs: [
      { label: 'Weight', value: '450 GSM Cross-Grain French Terry' },
      { label: 'Details', value: 'Ribbed side gussets and V-notch neck' },
      { label: 'Cuff', value: 'Tonal "SB" monogram on left sleeve' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'sb-bag-301',
    sku: 'SB-BAG-301',
    title: 'The "Data Room" Boat Tote',
    subtitle: '24 oz Heavy Duck Canvas',
    handle: 'data-room-boat-tote',
    category: 'canvas',
    price: 98.0,
    colorway: 'Natural Ecru with Navy Webbing',
    threadColor: 'Deep Navy Serif',
    undervisorColor: 'N/A',
    fabrication: '24 oz Heavy Industrial Duck Canvas with Double-Reinforced Bottom',
    hardware: 'Solid Antique Brass Key Clip & Heavy YKK Zipper',
    description:
      'Modeled after early 20th-century maritime coal totes. Crafted from stiff 24 oz unbleached duck canvas that stands upright on its own.',
    catalogStory:
      'Reinforced with double-stitched contrast webbing handles that wrap entirely around the base. Embroidered above the exterior slip pocket with "DATA ROOM". Fits laptops, prospectuses, and weekend kit.',
    stylingNotes: 'The definitive commuter and weekend travel companion.',
    images: ['/images/data_room_boat_tote.jpg', '/images/lifestyle_tote_car.jpg'],
    badges: ['24 oz Canvas'],
    inStock: true,
    featured: true,
    specs: [
      { label: 'Dimensions', value: '17" W x 15" H x 7" D' },
      { label: 'Fabric', value: '24 oz Unbleached Industrial Duck Canvas' },
      { label: 'Interior', value: 'Padded sleeve + YKK zippered pocket' },
      { label: 'Handles', value: 'Full-wrap continuous cotton webbing' },
    ],
  },
  {
    id: 'sb-bag-302',
    sku: 'SB-BAG-302',
    title: 'The "Management Fee" Dopp Kit',
    subtitle: 'Waxed Canvas & Brass',
    handle: 'management-fee-dopp-kit',
    category: 'canvas',
    price: 72.0,
    colorway: 'Dark Olive Waxed Canvas',
    threadColor: 'Tonal Olive Monogram',
    undervisorColor: 'N/A',
    fabrication: 'Heavy Waxed Cotton Canvas with Full-Grain Leather Trim',
    hardware: 'YKK Antique Brass Zipper with Leather Pull',
    description:
      'A compact waxed canvas dopp kit with full-grain leather trim and solid brass hardware for hotel counters and private travel.',
    catalogStory:
      'Built from water-resistant waxed canvas that develops a rich patina over time. The leather zipper pull is stamped with the Sponsor Backed crest. Sized to fit travel essentials cleanly.',
    stylingNotes: 'Hotel marble counters, weekend houses, and departures.',
    images: ['/images/management_fee_dopp_kit.jpg'],
    badges: ['New'],
    inStock: true,
    specs: [
      { label: 'Dimensions', value: '10" W x 5" H x 4" D' },
      { label: 'Fabric', value: 'Waxed cotton canvas with leather trim' },
      { label: 'Hardware', value: 'YKK antique brass zipper' },
      { label: 'Lining', value: 'Water-resistant nylon interior' },
    ],
  },
  {
    id: 'sb-acc-401',
    sku: 'SB-ACC-401',
    title: 'The "Closed Q4" Brass Coin',
    subtitle: 'Solid Die-Struck Brass',
    handle: 'closed-q4-brass-coin',
    category: 'accessories',
    price: 38.0,
    colorway: 'Antiqued Satin Brass',
    threadColor: 'N/A',
    undervisorColor: 'N/A',
    fabrication: 'Solid Die-Struck Brass with Hand-Polished Antiqued Finish',
    hardware: 'Protective Velveteen Presentation Pouch',
    description:
      'Heft. That\'s the first thing you notice. Struck from solid brass with an antiqued satin patina. Built for mahogany desks.',
    catalogStory:
      'Side A features the Sponsor Backed crest with "CAPITAL PRESERVATION". Side B features a Roman laurel wreath framing "CLOSED". A tactile reminder of deals signed and wires cleared.',
    stylingNotes: 'Sits on mahogany desks.',
    images: ['/images/closed_q4_brass_coin.jpg'],
    badges: ['Solid Brass'],
    inStock: true,
    specs: [
      { label: 'Diameter', value: '2.0 inches (50.8 mm)' },
      { label: 'Thickness', value: '4.0 mm solid brass' },
      { label: 'Weight', value: '85 grams' },
    ],
  },
  {
    id: 'sb-acc-402',
    sku: 'SB-ACC-402',
    title: 'The Horween Leather Crest Key Fob',
    subtitle: 'Chicago Chromexcel & Brass',
    handle: 'leather-crest-key-fob',
    category: 'accessories',
    price: 20.0,
    colorway: 'Dark Brown Chromexcel',
    threadColor: 'N/A',
    undervisorColor: 'N/A',
    fabrication: 'Horween Chromexcel Full-Grain Leather (Chicago, IL)',
    hardware: 'Solid Antique Brass Split Ring & Rivet',
    description:
      'Cut from legendary Horween Chromexcel leather and hot-stamped with the Sponsor Backed crest. The definitive daily carry piece.',
    catalogStory:
      'Horween has tanned leather on the Chicago River since 1905. Stamped with our crest and paired with solid antique brass hardware, it will develop a rich, buttery patina over years of weekend travel and key turnings.',
    stylingNotes: 'Keys to the vintage Wagoneer or weekend retreat.',
    images: ['/images/leather_crest_key_fob.jpg'],
    badges: ['Horween Leather'],
    inStock: true,
    specs: [
      { label: 'Leather', value: 'Horween Chromexcel Full-Grain' },
      { label: 'Hardware', value: 'Solid antique brass split ring' },
      { label: 'Origin', value: 'Handcrafted in USA' },
    ],
  },
];

export function getProductByHandle(handle: string): Product | undefined {
  return PRODUCTS.find((p) => p.handle === handle);
}

export function getProductsByCategory(category: string): Product[] {
  if (category === 'all') return PRODUCTS;
  return PRODUCTS.filter((p) => p.category === category);
}
