import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'sb-cap-001',
    sku: 'SB-CAP-001',
    title: 'The "Sponsor Backed" Broken-In Chino Cap',
    subtitle: 'Volume I Flagship • Unstructured 6-Panel',
    handle: 'sponsor-backed-cap',
    category: 'caps',
    price: 64.0,
    wholesaleCost: 10.5,
    colorway: 'Boardroom Navy',
    threadColor: 'Ecru Collegiate Serif',
    undervisorColor: 'Augusta Green Cotton Twill',
    fabrication: '100% Long-Staple Cotton Chino Twill (7.5 oz, Stone Enzyme Washed)',
    hardware: 'Solid Antique Brass Tri-Glide Slider with Tuck-in Grommet',
    description:
      'In private equity, being "sponsor-backed" means your enterprise is fortified by top-tier institutional equity and seasoned operational partners. Worn on the weekend, it is an understated nod to the discipline of the buy-side.',
    catalogStory:
      'Our flagship piece. We start with 100% long-staple cotton chino twill, put it through a 45-minute stone enzyme wash to soften the fibers, and stitch "SPONSOR BACKED" arched across the crown in vintage ecru thread. The underside of the bill features our signature dark Augusta Green cotton twill—just like the classic 1980s American ballcaps.',
    stylingNotes:
      'Pair with an unbuttoned pale-blue Oxford, weathered chinos, and an early morning coffee run before markets open.',
    images: ['/images/sponsor_backed_cap.jpg'],
    badges: ['Volume I Flagship', 'Crafted in Dallas, TX'],
    inStock: true,
    featured: true,
    specs: [
      { label: 'Crown Profile', value: 'Low-profile unstructured 6-panel' },
      { label: 'Embroidery', value: 'High-density chain-stitched collegiate arch (1.0" height)' },
      { label: 'Hardware', value: 'Matte antique brass tri-glide slider' },
      { label: 'Undervisor', value: 'Glare-reducing Augusta Green cotton twill' },
      { label: 'Internal Taping', value: 'Custom satin tape with woven Hatco Dallas seal' },
    ],
    sizes: ['One Size Fits Most (21" - 24" Circumference)'],
  },
  {
    id: 'sb-cap-002',
    sku: 'SB-CAP-002',
    title: 'The "EBITDA" 5-Panel Braided Rope Cap',
    subtitle: 'Country Club Heritage • Performance Poly-Twill',
    handle: 'ebitda-rope-hat',
    category: 'caps',
    price: 68.0,
    wholesaleCost: 11.75,
    colorway: 'Augusta Cypress Green',
    threadColor: 'Bone Athletic Serif',
    undervisorColor: 'Matching Cypress Green with 5mm Chalk Braided Rope',
    fabrication: 'Water-resistant, matte-finish performance poly-cotton blend',
    hardware: 'Retro 7-hole perforated snapback',
    description:
      'The foundational financial metric meets the golden age of country club golf. Built with a medium-profile 5-panel crown and an authentic 5mm braided chalk cord resting across the visor seam.',
    catalogStory:
      'Whether you are breaking 80 on a Friday partner scramble or debating the merits of non-recurring add-backs over lunch at the grill, this cap signals instant belonging.',
    stylingNotes:
      'Worn with a pique polo and tortoiseshell sunglasses on the country club fairway deck.',
    images: ['/images/ebitda_rope_hat.jpg'],
    badges: ['Country Club Edition', 'Dallas Embroidered'],
    inStock: true,
    featured: true,
    specs: [
      { label: 'Crown Profile', value: 'Medium-profile 5-panel pinch-front' },
      { label: 'Rope Detail', value: '5mm braided chalk-white cotton cord' },
      { label: 'Embroidery', value: 'Crisp flat satin-stitch lettering' },
      { label: 'Sweatband', value: 'Moisture-wicking micro-terry' },
    ],
    sizes: ['One Size Fits Most (Adjustable Snapback)'],
  },
  {
    id: 'sb-cap-003',
    sku: 'SB-CAP-003',
    title: 'The "Dry Powder" Broken-In Chino Cap',
    subtitle: 'Classic Allocator • Washed Chino Twill',
    handle: 'dry-powder-cap',
    category: 'caps',
    price: 64.0,
    wholesaleCost: 10.5,
    colorway: 'Deep Midnight Navy',
    threadColor: 'Vintage Cream Roman Serif',
    undervisorColor: 'Augusta Green Cotton Twill',
    fabrication: '100% Long-Staple Cotton Chino Twill (Stone Washed)',
    hardware: 'Solid Antique Brass Tri-Glide Slider',
    description:
      'Uninvested capital committed by LPs, waiting on the sidelines to be deployed. A double meaning evoking classic 19th-century dry goods merchants and unyielding liquidity.',
    catalogStory:
      'Inspired by the weathered ballcaps tossed onto the passenger seats of vintage Wagoneers parked outside Maidstone Club. Cut from washed chino twill with chain-stitched typography that feels broken-in from day one.',
    stylingNotes: 'Worn with a heavy knit Shetland crewneck or a vintage canvas chore coat.',
    images: ['/images/dry_powder_cap.jpg'],
    badges: ['Core Allocator', 'Dallas Embroidered'],
    inStock: true,
    featured: true,
    specs: [
      { label: 'Crown Profile', value: 'Low-profile unstructured 6-panel' },
      { label: 'Lettering', value: 'Arched Roman serif' },
      { label: 'Hardware', value: 'Antique brass slider' },
      { label: 'Undervisor', value: 'Augusta Green twill' },
    ],
    sizes: ['One Size Fits Most (21" - 24" Circumference)'],
  },
  {
    id: 'sb-cap-004',
    sku: 'SB-CAP-004',
    title: 'The "Pls Fix" Minimalist Chino Cap',
    subtitle: 'The 11:42 PM Email • Micro-Typewriter Font',
    handle: 'pls-fix-cap',
    category: 'caps',
    price: 58.0,
    wholesaleCost: 9.8,
    colorway: 'Washed Slate Grey',
    threadColor: 'Midnight Navy Micro-Stitch',
    undervisorColor: 'Augusta Green Cotton Twill',
    fabrication: '100% Brushed Chino Cotton Twill',
    hardware: 'Matte Brushed Pewter Slider',
    description:
      'The notorious two-word sign-off sent by partners from the backseat of an Uber at 11:42 PM. Rendered in a tiny, razor-sharp typewriter font that is intentionally discreet.',
    catalogStory:
      'To anyone outside the industry, it is just two lowercase words. To anyone who has ever spent a Saturday night aligning footnotes in an Investment Committee memo, it is pure, shared catharsis.',
    stylingNotes: 'Quiet, wry, and understated with an unbuttoned OCBD in the terminal bullpen.',
    images: ['/images/sponsor_backed_cap.jpg'],
    badges: ['Associate Cult Favorite', 'Dallas Embroidered'],
    inStock: true,
    specs: [
      { label: 'Typography', value: '0.45" lowercase Courier typewriter micro-embroidery' },
      { label: 'Crown Profile', value: 'Unstructured 6-panel relaxed fit' },
      { label: 'Hardware', value: 'Matte brushed pewter slider' },
    ],
    sizes: ['One Size Fits Most'],
  },
  {
    id: 'sb-cap-005',
    sku: 'SB-CAP-005',
    title: 'The "2 & 20" Stealth Strapback',
    subtitle: 'Tonal Midnight Black • High-Density Puff',
    handle: 'two-and-twenty-cap',
    category: 'caps',
    price: 62.0,
    wholesaleCost: 10.2,
    colorway: 'Weathered Charcoal',
    threadColor: 'Tonal Black 3D Puff',
    undervisorColor: 'Charcoal Cotton Twill',
    fabrication: '100% Heavy-Washed Charcoal Chino Twill',
    hardware: 'Gunmetal Slider Buckle',
    description:
      'The foundational GP fee structure: two percent management fee, twenty percent carried interest. Stitched in subtle tonal embroidery for pure stealth-wealth authority.',
    catalogStory:
      'From five paces away, it appears to be a clean, unadorned black cap. Up close, it commands instant respect from fellow fund managers.',
    stylingNotes: 'Worn with a cashmere half-zip and dark denim on private departures.',
    images: ['/images/sponsor_backed_cap.jpg'],
    badges: ['Stealth Edition', 'Dallas Embroidered'],
    inStock: true,
    specs: [
      { label: 'Front Mark', value: 'Tonal 3D puff "2 & 20"' },
      { label: 'Rear Arch', value: 'Micro-embroidered "SB Co." monogram' },
      { label: 'Hardware', value: 'Gunmetal slider buckle' },
    ],
    sizes: ['One Size Fits Most'],
  },
  {
    id: 'sb-cap-006',
    sku: 'SB-CAP-006',
    title: 'The "Carried Interest" 14-Wale Corduroy Cap',
    subtitle: 'Autumn Release • Tactile 14-Wale Cord',
    handle: 'carried-interest-corduroy',
    category: 'caps',
    price: 68.0,
    wholesaleCost: 12.5,
    colorway: 'Oxblood Merlot',
    threadColor: 'Vintage Antique Gold Cursive',
    undervisorColor: 'Matching Oxblood Corduroy',
    fabrication: '100% Fine-Wale Cotton Corduroy (14-wale count)',
    hardware: 'Solid Antique Brass Buckle',
    description:
      'The GP’s 20% share of fund profits; the pinnacle status metric in private equity. Cut from substantial 14-wale cotton corduroy in a deep autumn wine tone.',
    catalogStory:
      'Evokes leather wingback chairs and October flights to Boston. Embroidered with "Carried Interest" in an elegant, cursive script that looks more like a private society emblem than a finance term.',
    stylingNotes: 'Worn with heavy cable-knit sweaters and espresso during Q4 deal sprints.',
    images: ['/images/ebitda_rope_hat.jpg'],
    badges: ['Autumn Limited', 'Dallas Embroidered'],
    inStock: true,
    specs: [
      { label: 'Fabric', value: '100% Cotton 14-Wale Corduroy' },
      { label: 'Embroidery', value: 'Vintage gold heritage script' },
      { label: 'Hardware', value: 'Antique brass tri-glide slider' },
    ],
    sizes: ['One Size Fits Most'],
  },
  {
    id: 'sb-bag-301',
    sku: 'SB-BAG-301',
    title: 'The "Data Room" 24 oz Heavy Canvas Boat Tote',
    subtitle: 'Indestructible Duck Canvas • YKK Brass Zipper',
    handle: 'data-room-boat-tote',
    category: 'canvas',
    price: 98.0,
    wholesaleCost: 22.0,
    colorway: 'Natural Ecru Canvas with Boardroom Navy Webbing',
    threadColor: 'Deep Navy Serif',
    undervisorColor: 'N/A',
    fabrication: '24 oz Heavy Industrial Duck Canvas with Double-Reinforced Bottom',
    hardware: 'Solid Antique Brass Key Clip & Heavy YKK Zipper',
    description:
      'Modeled after early 20th-century maritime coal totes. Crafted from stiff 24 oz unbleached duck canvas that stands upright on its own on a tarmac or commuter floor.',
    catalogStory:
      'Reinforced with double-stitched contrast webbing handles that wrap entirely around the base for structural support. Embroidered above the exterior slip pocket with "DATA ROOM". Large enough for two 15" laptops, pitchbooks, and weekend kit.',
    stylingNotes: 'The definitive Hamptons jitney or Grand Central commuter companion.',
    images: ['/images/data_room_boat_tote.jpg'],
    badges: ['24 oz Heavy Duck', 'Dallas Embroidered'],
    inStock: true,
    featured: true,
    specs: [
      { label: 'Dimensions', value: '17" W x 15" H x 7" D' },
      { label: 'Fabric Weight', value: '24 oz Unbleached Industrial Duck Canvas' },
      { label: 'Internal Storage', value: 'Padded laptop sleeve + YKK zippered security pocket' },
      { label: 'Handles', value: 'Full-wrap continuous load-bearing cotton webbing' },
    ],
  },
  {
    id: 'sb-tee-101',
    sku: 'SB-TEE-101',
    title: 'The "Adjusted EBITDA*" Heavyweight Pocket Tee',
    subtitle: '260 GSM Combed Cotton • Boxy Vintage Fit',
    handle: 'adjusted-ebitda-tee',
    category: 'apparel',
    price: 54.0,
    wholesaleCost: 14.5,
    colorway: 'Southampton Chalk White',
    threadColor: 'Navy Micro-Serif with Antique Brass Asterisk',
    undervisorColor: 'N/A',
    fabrication: '100% Ring-Spun Combed Cotton (260 GSM / 7.7 oz)',
    hardware: 'Hand-Stitched Woven Dallas Hem Tag',
    description:
      'A heavyweight tee with structure, weight, and zero cling. Knitted in the USA from dense 260 GSM combed cotton that washes down into an incredibly soft vintage hand.',
    catalogStory:
      'Features a reinforced chest pocket crowned with our discreet micro-embroidered mark: "ADJUSTED*" with the asterisk subtly rendered in golden brass thread. (Footnote explaining add-backs not included).',
    stylingNotes: 'Worn with rolled chinos or swim trunks on Summer Fridays.',
    images: ['/images/sponsor_backed_cap.jpg'],
    badges: ['USA Knitted', 'Dallas Embroidered'],
    inStock: true,
    specs: [
      { label: 'Fabric Weight', value: '260 GSM / 7.7 oz Heavyweight Combed Cotton' },
      { label: 'Collar', value: '1" Sturdy ribbed crewneck collar that will not bacon' },
      { label: 'Fit', value: 'Classic 90s J. Crew relaxed boxy cut with drop shoulder' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'sb-swt-201',
    sku: 'SB-SWT-201',
    title: 'The "Sunday Night Deck" French Terry Sweatshirt',
    subtitle: '450 GSM Loopback Terry • Ribbed Side Gussets',
    handle: 'sunday-night-deck-sweatshirt',
    category: 'apparel',
    price: 118.0,
    wholesaleCost: 28.0,
    colorway: 'Collegiate Navy',
    threadColor: 'Tonal Monogram Cuff Stitch',
    undervisorColor: 'N/A',
    fabrication: '450 GSM 100% Cotton Loopback French Terry (Cross-Grain Cut)',
    hardware: 'Ribbed V-Notch Collar Insert',
    description:
      'Named after the Sunday evening ritual of putting the final touches on Monday morning’s 8:30 AM presentation. Crafted from substantial 450 GSM cross-grain loopback French terry with heavy ribbed side gussets.',
    catalogStory:
      'It has the weight, drape, and warmth of the classic collegiate sweatshirts our fathers wore to Ivy League football games. Finished with a discreet tonal "SB" monogram stitched on the left wrist cuff.',
    stylingNotes: 'Layered over a white t-shirt with broken-in fatigues or grey flannel trousers.',
    images: ['/images/ebitda_rope_hat.jpg'],
    badges: ['Heavyweight 450 GSM', 'Dallas Finished'],
    inStock: true,
    specs: [
      { label: 'Weight', value: '450 GSM Cross-Grain French Terry' },
      { label: 'Details', value: 'Ribbed side gussets and classic V-notch neck' },
      { label: 'Cuff Stitch', value: 'Micro tonal monogram on left sleeve' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'sb-acc-401',
    sku: 'SB-ACC-401',
    title: 'The "Closed Q4" Solid Die-Struck Brass Challenge Coin',
    subtitle: 'Desk Paperweight • 85 Grams Solid Brass',
    handle: 'closed-q4-brass-coin',
    category: 'accessories',
    price: 38.0,
    wholesaleCost: 7.5,
    colorway: 'Antiqued Satin Brass',
    threadColor: 'N/A',
    undervisorColor: 'N/A',
    fabrication: 'Solid Die-Struck Brass with Hand-Polished Antiqued Finish',
    hardware: 'Protective Velveteen Presentation Pouch',
    description:
      'Heft. That is the first thing you notice. Struck from solid brass with an antiqued satin patina that resists fingerprints. Built to sit on mahogany desks atop stacks of acquisition documents.',
    catalogStory:
      'Side A features the Sponsor Backed crest with "CAPITAL PRESERVATION". Side B features an engraved Roman laurel wreath framing "CLOSED". A tactile reminder of deals signed and wires cleared.',
    stylingNotes: 'Sits next to a Montblanc pen on mahogany desks or executive credenzas.',
    images: ['/images/data_room_boat_tote.jpg'],
    badges: ['Solid Brass', 'Dealmaker Keepsake'],
    inStock: true,
    specs: [
      { label: 'Diameter', value: '2.0 inches (50.8 mm)' },
      { label: 'Thickness', value: '4.0 mm solid brass plate' },
      { label: 'Weight', value: '85 grams (substantial desk presence)' },
    ],
  },
];

export function getProductByHandle(handle: string): Product | undefined {
  return PRODUCTS.find((p) => p.handle === handle);
}

export function getProductsByCategory(category: string): Product[] {
  if (category === 'all') return PRODUCTS;
  return PRODUCTS.filter((p) => p.category === category);
}
